resource_types:
- name: artifactory
  type: docker-image
  source:
    repository: pivotalservices/artifactory-resource
resources:    
- name: conversion-git-repo
  type: git
  source:
    uri: https://pepsicoit.visualstudio.com/LOTO/_git/pepsico-loto-document-conversion
    username: ((VSTS_USERNAME))
    password: ((VSTS_PASSWORD))
    branch: master
jobs:
- name: build_dev
  serial: true
  plan:
  - get: conversion-git-repo
    trigger: true
  - task: build_dev
    file: conversion-git-repo/ci/build.yml
    params:
         artifactory_userid: ((artifactory_username))
         artifactory_pass: ((artifactory_password))
         artifactory_path: ((artifactory_url))
         environment: dev
         
- name: unit_testing
  serial: true
  plan: 
    - get: conversion-git-repo
      passed: 
        - build_dev
      trigger: true
    - task: conversion_unit_test
      file: conversion-git-repo/ci/unittest.yml
- name: sonar_analysis
  public: true
  plan:
    - get: conversion-git-repo
      passed: 
       - unit_testing
      trigger: true
    - task: code-scan_testing
      file: conversion-git-repo/ci/sonarscan.yml
- name: fortify-scan
  public: true
  plan:
     - get: conversion-git-repo
       passed:
       - unit_testing
       trigger: true
     - task: code-scan_testing
       file: conversion-git-repo/ci/scan.yml
       params:
         artifactory_username: ((artifactory_username))
         artifactory_password: ((artifactory_password))
         artifactory_url: ((artifactory_url))
         environment: dev
         
 
- name: deploy-jar-to-Artifactory
  public: true
  plan:
   - get: conversion-git-repo
     passed:
      - fortify-scan
      - sonar_analysis
     trigger: true
   - task: copy-jar-file
     file: conversion-git-repo/ci/copyfile.yml
     params:
       artifactory_username: ((artifactory_username))
       artifactory_password: ((artifactory_password))
       artifactory_url: ((artifactory_url))
       environment: dev
       
########################################################