resource_types:
- name: muntha123
  type: docker-image
  source:
    repository: nulldriver/cf-cli-resource
resources:    
- name: deploying-application
  type: git
  source:
    uri: https://github.com/muntha123/deploying-application.git
    #username: ((VSTS_USERNAME))
    #password: ((VSTS_PASSWORD))
    branch: master

jobs:
- name: deploy
  serial: true
  plan:
  - get: deploying-application
    trigger: true
  - task: deploy
    file: deploying-application/ci/build.yml
    params:
         #artifactory_userid: ((artifactory_username))
         #artifactory_pass: ((artifactory_password))
         #artifactory_path: ((artifactory_url))
         #environment: dev
         API_ENDPOINT: ((cf-api))
         USERNAME: ((concourse-automation-client-id))
         PASSWORD: ((concourse-automation-client-secret))
         ORG: ((cf-org))
         SPACE: ((cf-space))
